spring:
  application:
    name: gigachat-api-server

gigachat:
  auth-key: MDE5YThlMjctNDJiMS03NzRjLWE4ZDAtMzM2NzEwMWFmNTAxOmQ0YzRhZmY3LTc2MWMtNGQxMC1hYzU3LTE5MGNjNDgzODNiMg==


logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
