spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    eureka:
      client:
        initial-instance-info-retry-interval-seconds: 5
        max-retries: 10
    config:
      server:
        native:
          search-locations:
            - "classpath:config/core/{application}"
            - "classpath:config/infra/{application}"
server:
  port: 8888
eureka:
  client:
    initial-instance-info-retry-interval-seconds: 5
    max-retries: 10
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10

