name: Java CI â€“ Build Multi-Module

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-all-modules:
    name: Build & test all modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Comment out lines in application.yaml for tests
        run: |
          sed -i 's/^\s*config:/# &/' allergint/core/diary-service/src/main/resources/application.yaml
          sed -i 's/^\s*import: "configserver:"/# &/' allergint/core/diary-service/src/main/resources/application.yaml
          sed -i 's/^\s*config:/# &/' allergint/core/user-service/src/main/resources/application.yaml
          sed -i 's/^\s*import: "configserver:"/# &/' allergint/core/user-service/src/main/resources/application.yaml
      - name: Build all modules
        run: |
          cd allergint/core
          mvn clean install -B -pl interaction-api,user-service,diary-service -am -DskipTests=false
